NISQ-Analyzer Plugin
UST-QuAntiL/qhana-docker pull request #6
Opened 2022-09-29 10:49 UTC by cloudsftp

Add necessary containers for the NISQ-Analyzer plugin

2022-10-05 09:03 UTC, cloudsftp commented
Going to update the user documentation in this PR as well

2022-10-14 14:36 UTC, buehlefs approved these changes

2022-10-14 14:36 UTC, buehlefs commented on docker-compose.yml
> +    image: postgres
`profiles` is missing

2022-10-21 06:54 UTC, salmma requested changes
Comments regarding quickstart.md
- "The inputs can be validated with the "validate" button." - please set a "valid" when the input for a plugin is correct - otherwise the user doesn't know if it worked
- "The title of the output directly links to the produced output data detaisl page. The page contains adownload link and a preview." fix typos.
- "Once the results are available the UI will show the outputs generated by the plugin in the open timeline step." - all screenshots afterwards are old (the menu bar is changed) please update - otherwise it is confusing for the user

<img width="1611" alt="Bildschirmfoto 2022-10-21 um 08 51 44" src="https://user-images.githubusercontent.com/23473511/197131613-af9cfa41-38e5-4bc9-899c-18eedfb32538.png">
How can the user now start the analysis of an implementation after start up? It is not clear how to add an implementation - please add documentation.

2022-10-21 06:54 UTC, salmma commented on readme.md
> +If you want to use the NISQ-Analyzer plugin, use `docker-compose --profile nisq up`.
add a link to the nisq analyzer repo

2022-10-21 07:22 UTC, salmma requested changes
please also motivate the nature of templates: for what do they exist, how are they defined, who can define them, etc.

2022-10-21 09:52 UTC, cloudsftp commented
> "The inputs can be validated with the "validate" button." - please set a "valid" when the input for a plugin is correct - otherwise the user doesn't know if it worked

I did not understand this point.

2022-10-21 09:56 UTC, salmma commented
> > "The inputs can be validated with the "validate" button." - please set a "valid" when the input for a plugin is correct - otherwise the user doesn't know if it worked
> 
> I did not understand this point.

In the UI, when the user clicks on the "validate" button there is no hint that the input is valid (eg green small text or a green checkmark next to it), instead nothing happens

2022-10-21 10:03 UTC, buehlefs commented
Changing the validate button behaviour is way out of scope for this PR. I've opened an Issue in the plugin runner repo for this <https://github.com/UST-QuAntiL/qhana-plugin-runner/issues/46>
@cloudsftp If you want to fix it, then you can, but I think that this is not part of your project (meaning that I am responsible to fix that).

2022-10-21 10:44 UTC, salmma commented
> Changing the validate button behaviour is way out of scope for this PR. I've opened an Issue in the plugin runner repo for this [UST-QuAntiL/qhana-plugin-runner#46](https://github.com/UST-QuAntiL/qhana-plugin-runner/issues/46)
> @cloudsftp If you want to fix it, then you can, but I think that this is not part of your project (meaning that I am responsible to fix that).

the main thing is to fix it 🙃

2022-11-02 10:19 UTC, salmma requested changes
only one comment, rest looks good :)

2022-11-07 09:02 UTC, salmma approved these changes
LG

2022-11-07 14:23 UTC, merged